Include TeamComposition in Pick for foreign key
InvalidRequestError: When initializing mapper Mapper|Pick|picks, expression 'TeamComposition' failed to locate a name ("name 'TeamComposition' is not defined"). If this is a class name, consider adding this relationship() to the <class 'src.db.models.pick.Pick'> class after both dependent classes have been defined.